name: Main

on:
  push:
    branches: ['feat/**', 'track/**']
  pull_request:
    branches: [nwl]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  unit-test-node:
    uses: ./.github/workflows/unit-test-node.yml
